'''
This file holds the constants 

-----
'''

all = [
    'DATA_DIR',
    'BANK_STATEMENTS_DIR',
    'CLASSIFIED_TRANSACTIONS','_DIR',
    'CLASSIFICATION_JSON_DIR',
    'CLASSIFICATION_JSON_DIR_LVL_1',
    'CLASSIFICATION_JSON_DIR_LVL_2',
]

DATA_DIR = 'data/'
BANK_STATEMENTS_DIR = DATA_DIR + 'bank_statements/'
CLASSIFIED_TRANSACTIONS_DIR = DATA_DIR + 'classified_transactions/'
CLASSIFICATION_JSON_DIR = DATA_DIR + 'classification/'




CLASSIFICATION_JSON_DIR_LVL_1 = CLASSIFICATION_JSON_DIR + "level_1.json"
CLASSIFICATION_JSON_DIR_LVL_2 = CLASSIFICATION_JSON_DIR + "level_2.json"
